name: Netch CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - name: Build
        shell: pwsh
        run: |
          .\build.ps1

      - name: Upload
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          name: Netch
          path: Netch\bin\x64\Release\win-x64\publish\